// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qionpicrrboyktnsilgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpb25waWNycmJveWt0bnNpbGdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTc5MzksImV4cCI6MjA2MzgzMzkzOX0.QLnVrGPA1ZHrv8G0ieGx5Efh5xliKAsRcfW1TTx5x0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);